### PR TITLE
Moderator modules cleanup

### PR DESCRIPTION
**Pull request by orrinjelo**
- Cleans up all the .get() methods in favor of their .getString(), .getInteger(), .getBoolean(), etc. counterparts.  
- Fixed and updated `slowmode`, including implementing indefinite slowmode.

### CODE REVIEW

**Review by BobbyTheCatfish — COMMENTED** [review]
looks good, but throw a // @ts-check at the start of the file. that might show some type errors and we want to make sure all of those are cleared up.

**Comment by BobbyTheCatfish** [comment]
have you updated augur lately? there was a bug fix last week that fixed having to add all of the addcommand options

**Comment by orrinjelo** [comment]
Aside from completely reinstalling everything, I haven't.  Looks like I'm on 3.0.9.

**Comment by BobbyTheCatfish** [comment]
it should be set to use the github link instead of the npm link

**Comment by orrinjelo** [comment]
It is. 
        "augurbot-ts": "github:BobbyTheCatfish/augurbot",
        ...
    "node_modules/augurbot-ts": {
      "version": "3.0.9",
      "resolved": "git+ssh://git@github.com/BobbyTheCatfish/augurbot.git#6141b8f4d33735a5a9eefcd8af98a171e161517b",
      "license": "MIT",
      "peerDependencies": {
        "axios": "^1.5.0",
        "discord.js": ">=14.x"
      }
    },

**Review by LDSGOhGo — APPROVED** [review]
Looks good to me (I have no idea what I'm doing)

**Comment by BobbyTheCatfish** [comment]
merging to new branch

**Pull request merged**
